import { AggregateApiResponse } from "../types/aggregateApiResponse";

const dummyData = {
  "Avg Consecutive Dot Balls": 2,
  "Avg First Boundary Ball": 7.7,
  "Balls Bowled": 6,
  "Balls Faced": 69,
  "Balls Faced MeanAD": 7.62,
  Batting: "Right hand",
  "Batting Avg": 17.67,
  "Batting S/R": 76.8,
  "Batting S/R MeanAD": 26.78,
  "Boundary %": 10.1,
  "Boundary Given %": 0,
  "Boundary Given Rate": "Infinity",
  "Boundary Rate": 9.9,
  "Bowled Outs": 0,
  Bowleds: 0,
  Bowling: "Right arm pace",
  "Bowling Avg": "Infinity",
  "Bowling Avg MeanAD": 0,
  "Bowling S/R": "Infinity",
  "Bowling S/R MeanAD": 0,
  Catches: 1,
  "Caught Outs": 3,
  "Caught and Bowled Outs": 0,
  "Caught and Bowleds": 0,
  Caughts: 0,
  "Dismissal Rate": 23,
  "Dot Ball %": 0.6,
  "Dot Ball Bowled %": 66.7,
  "Dot Balls": 43,
  "Dot Balls Bowled": 4,
  Drawn: 0,
  "Economy Rate": 4,
  "Economy Rate MeanAD": 0,
  Extras: 0,
  Fours: 4,
  Foursgiven: 0,
  Games: 4,
  "Hitwicket Outs": 0,
  Hitwickets: 0,
  "Innings Batted": 4,
  "Innings Bowled": 1,
  "LBW Outs": 0,
  LBWs: 0,
  "Mean Balls Faced": 17.2,
  "Mean Score": 13.25,
  "No Balls": 0,
  Outs: 3,
  "Run Outs": 0,
  Runouts: 0,
  Runs: 53,
  "Runs AA": -312.8,
  "Runs Rate": 4.6,
  "Runs/Ball": 0.8,
  "Runs/Ball AA": 0.1,
  Runsgiven: 4,
  "Runsgiven AA": -376.8,
  "Runsgiven/Ball": 0.7,
  "Runsgiven/Ball AA": -0.2,
  "Runsgiven/Wicket": "Infinity",
  "Score MeanAD": 6.12,
  "Scoring Consistency": 53.8,
  Singles: 15,
  Singlesgiven: 0,
  Sixes: 3,
  Sixesgiven: 0,
  "Strike Turnover %": 36.6,
  "Strike Turnovergiven %": 16.7,
  "Stumped Outs": 0,
  Stumpeds: 0,
  Stumpings: 0,
  "Survival Consistency": 55.7,
  Wickets: 0,
  Wides: 0,
  "Win %": 100,
  Won: 4,
};

export function replaceNullData(data: AggregateApiResponse) {
  const keys = Object.keys(data);

  keys.forEach((key) => {
    if (data[key] === null) {
      data[key] = dummyData;
    }
  });

  return data;
}
